#!/usr/bin/env bash
# Stand up the Gemma 4 vLLM serving from scripts/config.conf.
#   ./up.sh                    # generate overlay, apply, wait for Ready, print endpoint
#   ./up.sh --no-wait          # apply and return immediately (don't block on rollout)
#   ./up.sh --mode kserve      # override SERVE_MODE for this run (else config.conf/env)
#
# SERVE_MODE selects the mechanism (set in config.conf, or per-run via --mode / env):
#   lazy   = plain Deployment; vLLM pulls weights from HF into the Pure PVC.
#   kserve = seed Job stages weights onto the PVC, then a KServe InferenceService
#            serves them from pvc://model-cache.
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"
parse_mode_flag "$@"; set -- ${REST_ARGS[@]+"${REST_ARGS[@]}"}
load_config

WAIT=1
[ "${1:-}" = "--no-wait" ] && WAIT=0

# Split IMAGE into name and tag for the kustomize images transformer.
if [[ "$IMAGE" == *:* ]]; then
  IMAGE_NAME="${IMAGE%:*}"; IMAGE_TAG="${IMAGE##*:}"
else
  IMAGE_NAME="$IMAGE"; IMAGE_TAG="latest"
fi

# ---------------------------------------------------------------------------
# Generate the overlay. The shared header (namespace, base, configmap, image) is
# identical across modes; only the component and the resource patches differ.
# ---------------------------------------------------------------------------
info "Generating overlay ($SERVE_MODE) -> $OVERLAY_DIR"
mkdir -p "$OVERLAY_DIR"
cat >"$OVERLAY_DIR/kustomization.yaml" <<EOF
# GENERATED by scripts/up.sh from scripts/config.conf — do not edit by hand.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${NAMESPACE}

resources:
  - ../../base

# Serving mechanism for SERVE_MODE=${SERVE_MODE}.
components:
  - ../../components/${SERVE_MODE}

# Override the tunable vLLM args from config.conf (consumed by the lazy
# Deployment; the kserve runtime gets the same values via the args patch below).
configMapGenerator:
  - name: gemma4-params
    behavior: merge
    literals:
      - MODEL_ID=${MODEL_ID}
      - SERVED_NAME=${SERVED_NAME}
      - TP_SIZE=${TP_SIZE}
      - MAX_MODEL_LEN=${MAX_MODEL_LEN}
      - GPU_MEM_UTIL=${GPU_MEM_UTIL}

# Override the image (name + tag) — matches the container in both the Deployment
# and the ServingRuntime.
images:
  - name: docker.io/vllm/vllm-openai
    newName: ${IMAGE_NAME}
    newTag: "${IMAGE_TAG}"

EOF

# Mode-specific patches (appended to the overlay above).
if [ "$SERVE_MODE" = "lazy" ]; then
  cat >>"$OVERLAY_DIR/kustomization.yaml" <<EOF
# GPU count and PVC size are resource fields — patched here, not via ConfigMap.
patches:
  - target: { kind: Deployment, name: gemma4-vllm }
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/nvidia.com~1gpu
        value: "${GPU_COUNT}"
  - target: { kind: PersistentVolumeClaim, name: model-cache }
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: ${STORAGE_SIZE}
EOF
else
  # kserve: inject the config.conf tunables into the runtime args (no ConfigMap —
  # kustomize does not rewrite ConfigMap refs inside a CRD), set the GPU limit,
  # point the InferenceService at the seeded PVC subpath, and size the PVC.
  cat >>"$OVERLAY_DIR/kustomization.yaml" <<EOF
patches:
  - target: { kind: ServingRuntime, name: gemma4-vllm-runtime }
    patch: |-
      - op: replace
        path: /spec/containers/0/args
        value:
          - "--model=/mnt/models"
          - "--served-model-name=${SERVED_NAME}"
          - "--tensor-parallel-size=${TP_SIZE}"
          - "--max-model-len=${MAX_MODEL_LEN}"
          - "--gpu-memory-utilization=${GPU_MEM_UTIL}"
          - "--port=8080"
      - op: replace
        path: /spec/containers/0/resources/limits/nvidia.com~1gpu
        value: "${GPU_COUNT}"
  - target: { kind: InferenceService, name: gemma4 }
    patch: |-
      - op: replace
        path: /spec/predictor/model/storageUri
        value: "pvc://model-cache/${MODEL_SUBPATH}"
  - target: { kind: PersistentVolumeClaim, name: model-cache }
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: ${STORAGE_SIZE}
EOF
fi

# Ensure the namespace exists (this account creates projects, not namespaces).
if ! oc get project "$NAMESPACE" >/dev/null 2>&1; then
  info "Creating project $NAMESPACE"
  oc new-project "$NAMESPACE" >/dev/null
fi

# Optional HF token secret (created/updated only if a token was provided).
if [ -n "$HF_TOKEN" ]; then
  info "Applying hf-token secret"
  oc create secret generic hf-token --from-literal=token="$HF_TOKEN" \
    -n "$NAMESPACE" --dry-run=client -o yaml | oc apply -f - >/dev/null
else
  info "No HF_TOKEN set — skipping secret (model is public; token is optional)."
fi

if [ "$SERVE_MODE" = "lazy" ]; then
  info "Applying manifests (oc apply -k)"
  oc apply -k "$OVERLAY_DIR"

  if [ "$WAIT" -eq 0 ]; then
    info "Applied. --no-wait given; not blocking on rollout."
    exit 0
  fi

  info "Waiting for rollout (first run downloads weights — can take ~15-20 min)..."
  oc rollout status deploy/gemma4-vllm -n "$NAMESPACE" --timeout=1800s
else
  # --- kserve: stage weights first, then serve ---------------------------------
  # Labeling the namespace is the one cluster-scoped mutation the kserve path
  # needs; a plain project user can't patch a Namespace, so this step (and only
  # this step) impersonates system:admin, per the repo convention.
  info "Enabling single-model serving (modelmesh-enabled=false)"
  oc label namespace "$NAMESPACE" modelmesh-enabled=false --overwrite \
    --as system:admin >/dev/null

  # The seed Job needs the PVC to exist. Create it at the configured size first
  # (idempotent — the overlay re-applies it below).
  info "Ensuring weight-cache PVC exists ($STORAGE_SIZE)"
  sed "s|storage: 150Gi|storage: ${STORAGE_SIZE}|" "$BASE_DIR/pvc.yaml" \
    | oc apply -n "$NAMESPACE" -f -

  # Stage the weights onto the PVC and wait for completion BEFORE serving, so the
  # InferenceService never starts vLLM against an empty /mnt/models.
  info "Seeding weights onto the PVC (huggingface -> /models/${MODEL_SUBPATH})"
  oc delete job gemma4-seed -n "$NAMESPACE" --ignore-not-found >/dev/null
  sed -e "s|__IMAGE__|${IMAGE}|g" \
      -e "s|__MODEL_ID__|${MODEL_ID}|g" \
      -e "s|__MODEL_SUBPATH__|${MODEL_SUBPATH}|g" \
      "$COMPONENTS_DIR/kserve/seed-job.yaml" \
    | oc apply -n "$NAMESPACE" -f -

  if [ "$WAIT" -eq 0 ]; then
    info "Seed Job submitted. --no-wait given; not blocking on seed or serving."
    exit 0
  fi

  # Seed time depends on HF-CDN egress; on a fast link the ~62GB pull is only a
  # few minutes, but budget generously for a cold/slow link.
  info "Waiting for seed Job to complete (downloads ~62GB — a few min to ~20 min)..."
  oc wait --for=condition=complete job/gemma4-seed -n "$NAMESPACE" --timeout=1800s

  info "Applying serving manifests (oc apply -k)"
  oc apply -k "$OVERLAY_DIR"

  info "Waiting for the InferenceService to become Ready..."
  oc wait --for=condition=Ready inferenceservice/gemma4 -n "$NAMESPACE" --timeout=1800s

  # KServe RawDeployment's predictor service isn't directly routable; publish an
  # explicit external service + edge route (same approach as the granite path).
  # IMPORTANT: create the route only AFTER the InferenceService is Ready. While the
  # isvc is still progressing, KServe actively reconciles it and prunes an
  # externally-facing route sharing the isvc's name (this isvc is cluster-local),
  # so a route created earlier gets deleted out from under us. Once Ready (steady
  # state) KServe leaves it alone. Idempotent, and errors are NOT swallowed
  # (a hidden failure once left a Ready isvc with no reachable endpoint).
  info "Creating external service and route"
  if ! oc get service gemma4-external -n "$NAMESPACE" >/dev/null 2>&1; then
    oc create service clusterip gemma4-external --tcp=80:8080 -n "$NAMESPACE"
  fi
  oc set selector service gemma4-external app=isvc.gemma4-predictor -n "$NAMESPACE"
  if ! oc get route "$ROUTE_NAME" -n "$NAMESPACE" >/dev/null 2>&1; then
    oc create route edge "$ROUTE_NAME" --service=gemma4-external --port=80-8080 \
      -n "$NAMESPACE"
  fi
fi

url="$(route_url)"
info "Ready. Endpoint: ${url:-<route pending>}"
echo
echo "  Test it:   ./test.sh"
echo "  Mode:      $SERVE_MODE"
echo "  Model:     $MODEL_ID  (served as '$SERVED_NAME', TP=$TP_SIZE on $GPU_COUNT GPU[s])"
