#!/usr/bin/env bash
# Stand up the Gemma 4 vLLM serving from scripts/config.conf.
#   ./up.sh            # generate overlay, apply, wait for Ready, print endpoint
#   ./up.sh --no-wait  # apply and return immediately (don't block on rollout)
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"
load_config

WAIT=1
[ "${1:-}" = "--no-wait" ] && WAIT=0

# Split IMAGE into name and tag for the kustomize images transformer.
if [[ "$IMAGE" == *:* ]]; then
  IMAGE_NAME="${IMAGE%:*}"; IMAGE_TAG="${IMAGE##*:}"
else
  IMAGE_NAME="$IMAGE"; IMAGE_TAG="latest"
fi

info "Generating overlay -> $OVERLAY_DIR"
mkdir -p "$OVERLAY_DIR"
cat >"$OVERLAY_DIR/kustomization.yaml" <<EOF
# GENERATED by scripts/up.sh from scripts/config.conf — do not edit by hand.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${NAMESPACE}

resources:
  - ../../base

# Override the tunable vLLM args from config.conf.
configMapGenerator:
  - name: gemma4-params
    behavior: merge
    literals:
      - MODEL_ID=${MODEL_ID}
      - SERVED_NAME=${SERVED_NAME}
      - TP_SIZE=${TP_SIZE}
      - MAX_MODEL_LEN=${MAX_MODEL_LEN}
      - GPU_MEM_UTIL=${GPU_MEM_UTIL}

# Override the image (name + tag).
images:
  - name: docker.io/vllm/vllm-openai
    newName: ${IMAGE_NAME}
    newTag: "${IMAGE_TAG}"

# GPU count and PVC size are resource fields — patched here, not via ConfigMap.
patches:
  - target: { kind: Deployment, name: gemma4-vllm }
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/nvidia.com~1gpu
        value: "${GPU_COUNT}"
  - target: { kind: PersistentVolumeClaim, name: model-cache }
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: ${STORAGE_SIZE}
EOF

# Ensure the namespace exists (this account creates projects, not namespaces).
if ! oc get project "$NAMESPACE" >/dev/null 2>&1; then
  info "Creating project $NAMESPACE"
  oc new-project "$NAMESPACE" >/dev/null
fi

# Optional HF token secret (created/updated only if a token was provided).
if [ -n "$HF_TOKEN" ]; then
  info "Applying hf-token secret"
  oc create secret generic hf-token --from-literal=token="$HF_TOKEN" \
    -n "$NAMESPACE" --dry-run=client -o yaml | oc apply -f - >/dev/null
else
  info "No HF_TOKEN set — skipping secret (model is public; token is optional)."
fi

info "Applying manifests (oc apply -k)"
oc apply -k "$OVERLAY_DIR"

if [ "$WAIT" -eq 0 ]; then
  info "Applied. --no-wait given; not blocking on rollout."
  exit 0
fi

info "Waiting for rollout (first run downloads weights — can take ~15-20 min)..."
oc rollout status deploy/gemma4-vllm -n "$NAMESPACE" --timeout=1800s

url="$(route_url)"
info "Ready. Endpoint: ${url:-<route pending>}"
echo
echo "  Test it:   ./test.sh"
echo "  Model:     $MODEL_ID  (served as '$SERVED_NAME', TP=$TP_SIZE on $GPU_COUNT GPU[s])"
