FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel

RUN pip install --no-cache-dir \
    "transformers==4.46.3" \
    "datasets==2.21.0" \
    "accelerate==1.1.1" \
    "peft==0.13.2" \
    "trl==0.12.1" \
    "bitsandbytes==0.44.1" \
    boto3 \
    scipy \
    sentencepiece \
    protobuf \
    rich

WORKDIR /scripts
