apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: net-test-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: net-test-vm
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          interfaces:
          - masquerade: {}
            name: default
        resources:
          requests:
            memory: 128Mi
      networks:
      - name: default
        pod: {}
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo
        name: containerdisk
