FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel

RUN pip install --no-cache-dir \
    "transformers==4.44.2" \
    "datasets==2.21.0" \
    "accelerate==0.33.0" \
    "peft==0.12.0" \
    "trl==0.10.1" \
    "bitsandbytes==0.43.3" \
    boto3 \
    scipy \
    sentencepiece \
    protobuf \
    rich

WORKDIR /scripts
