apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: minio-data-connection
parameters:
  - name: MINIO_ROOT_USER
    description: MinIO root user
    required: true
  - name: MINIO_ROOT_PASSWORD
    description: MinIO root password
    required: true
  - name: S3_ENDPOINT
    description: MinIO S3 endpoint URL
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: minio-data-connection
      labels:
        opendatahub.io/dashboard: 'true'
        opendatahub.io/managed: 'true'
      annotations:
        opendatahub.io/connection-type: s3
        openshift.io/display-name: MinIO Data Connection
    type: Opaque
    stringData:
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_S3_ENDPOINT: ${S3_ENDPOINT}
      AWS_S3_BUCKET: models
      AWS_DEFAULT_REGION: us-east-1
